### ISSUE TITLE
Release of ARM64 Supported Binaries

### ISSUE THREAD

**Issue by odidev** [Ashald/terraform-provider-stateful#2]
I was trying to build an arm64 image for **terraform-resource** package, but it was giving an issue as **terraform-provider-stateful** binary is not available for arm64 platform. I was able to build the linux binaries of **terraform-provider-stateful** for arm64 architecture locally without any code changes and verified it via file command.

```
arm139@ubuntuarm139:~/terraform-provider-stateful$ file release/terraform-provider-stateful_v1.1.0-6-g6d4f6c9-linux-arm64
release/terraform-provider-stateful_v1.1.0-6-g6d4f6c9-linux-arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=m-JJeA6y2-oUaQ6iUxiY/pimZLTqzv6CNoQcA7eNI/_cECx7YHOjJyB1U2gB4b/3uFouE3xhWtBIs9a_7Jr, not stripped

```

I am unable to find any arm64 specific binary in its [releases](https://github.com/ashald/terraform-provider-stateful/releases/tag/v1.1.0). Do you have any plan to release the arm64 binaries?

If required, I am happy to help.

**Comment by ashald** [comment]
Hi! Yeah, haven't envisioned demand for `arm64` when I released it last time, definitely need to add it.
I'm curios, what is `terraform-resource`?

**Comment by ashald** [comment]
Here it goes https://github.com/ashald/terraform-provider-stateful/releases/tag/v1.2.0 - thanks for helping this happen!
